language: java
jdk:
  - openjdk7
  - oraclejdk7

before_install:
  - sudo apt-get -qq install docker.io
  - sudo ln -sf /usr/bin/docker.io /usr/local/bin/docker
  - sudo sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io
  - sudo docker pull openshift/geard
  - sudo docker run -d openshift/geard
